### ISSUE TITLE
visualize an interface in your host with name "uetun1"

### ISSUE THREAD

**Issue by noormohammedli** [my5G/my5G-RANTester#14]
Hello sir, 
Thank you for sharing the code. 

I try to connect the code that you share my5G-core as in the picture below with my5G-RANTester to connect the UE and RAN with 5G Core. 

![Screenshot from 2021-02-28 18-10-24](https://user-images.githubusercontent.com/34620715/109424288-25515380-79f4-11eb-8631-754b78efac85.png)

![Screenshot from 2021-02-28 18-10-32](https://user-images.githubusercontent.com/34620715/109424768-313e1500-79f6-11eb-8f85-8f270df17ee6.png)

How can I know my registration done successfully? 
How can I visualize an interface with the name "uetun1"? 

Also, I tried your code for the docker (my5G-RANTester-docker), I don't know how can I view the interfaces with the prefix  "uetun" inside the Tester container. or create a virtual interface. 

Actually, with my5G-RANTester-docker code, it's run for the first time than the next day when I run the code the Tester container turn down and the other container on. 
I tried to make it up by using "docker start tester" and service docker restart. 

Regards,

**Comment by baleeiro17** [comment]
Hi, thank you for your interest in project.

How can I know my registration done successfully?
You will see an interface named uetun1, if everything working fine. And next you can testing data plane. If you don't see the interfaces please configure ue information in web ui(you can use script included_ues.sh from my5G-RANTester-docker). And restart you environment with docker-compose down and then using docker-compose up -d.

How can I visualize an interface with the name "uetun1"?
You can use command "ip a" or "ifconfig" in your host or tester's container. Then using command "ping google.com -I uetun1" to testing UE connectivity with internet.

Second image, gnb connect to core but UE doesn't connect to core. Did you add UE's information(imsi, opc, amf and k) in web ui of core? I think registration of UE is not complete.

**Comment by noormohammedli** [comment]
Hi, 
Thank you for your replay, 

How can I access the web UI, is it the same one in the my5G-core folder, 
there is a folder called webconsole, I run a file called server.go. 

If "server.go" is the right folder, I did it yesterday by adding the same information that you put in the image below but i did not get "uetun1" in my host. 
<img width="978" alt="Screenshot 2021-02-28 at 10 28 03 pm" src="https://user-images.githubusercontent.com/34620715/109430853-62c5d900-7a14-11eb-9402-6d30f7ce404f.png">

The "ifconfig" I put it in my tester's container but the "ifconfig" comment not recognize. 

When i use "ifconfig" in my host, I could see many interfaces but none of them called "uetun1", 

what I understand now the "uetun1" created when the UE registered successfully to the core. 

Regards.

**Comment by baleeiro17** [comment]
What I understand now the "uetun1" created when the UE registered successfully to the core.
Yes, You are correctly.

The "ifconfig" I put it in my tester's container but the "ifconfig" comment not recognize.
Testing with "ip a".

Can please show me, an image with all containers running in your host and Tester's log?
Using "docker ps" and "docker-compose logs tester". Before, you must running containers with "docker-compose up -d".

Let me know if you need any help further.
Thanks, Lucas.

**Comment by noormohammedli** [comment]
Hi Lucas, 
I will run the code and I will send you images for that. 

How can I access the web UI, is it the same one in the my5G-core folder,
there is a folder called webconsole. 

Can I run the code (the UE, RAN with Core ) without using docker? 

Thanks,

**Comment by baleeiro17** [comment]
How can I access the web UI, is it the same one in the my5G-core folder,
there is a folder called webconsole.

If you are using containers, you must verify if container web UI is running. If yes, open web browser in localhost:500 or you can run script included_ues.sh will automatically add UE information in web UI.

If you are not using containers, you are correctly. Then we need to investigate more deep the problem. Did you add imsi information in web ui ?

Can I run the code (the UE, RAN with Core ) without using docker?
Yes, you can but I think docker will help you with some configurations and others problems because is an environment automatized. All you need is run "docker-compose up -d" to testing 5g core.

that what i get when i run included_ues.sh
Hey you must use this link https://github.com/my5G/my5G-RANTester/wiki/Using-containers and this source code https://github.com/my5G/my5G-RANTester-docker.git .

I am new to this topic and I am trying to slice the 5G network or put different slice for each user. Do you have any idea about that, and I am sorry if I asked simple questions.
Yes, it is possible.

**Comment by noormohammedli** [comment]
Yes I add the imsi information in web ui as in the image below by using webconsole from my5G-core folder. 

![Screenshot from 2021-02-28 23-55-07](https://user-images.githubusercontent.com/34620715/109433416-467c6900-7a21-11eb-8f09-0137eb783b4a.png)

**Comment by baleeiro17** [comment]
Yes, it is correct. But you have to check if imsi in web ui is equal to imsi field in file config.yml https://github.com/my5G/my5G-RANTester/blob/master/config/config.yml. The default value is 2089300000001, you need to add this in web ui(without name imsi, ignore this please).

**Comment by noormohammedli** [comment]
Yes,  add the info below same in config file to the web ui

ue:
  imsi: "imsi-2089300000001"
  key: "70d49a71dd1a2b806a25abe0ef749f1e"
  opc: "6f1bf53d624b3a43af6592854e2444c7"

**Comment by baleeiro17** [comment]
yes, I think everything is fine now. Show me logs of my5gRANTester. Please.

**Comment by noormohammedli** [comment]
I get [UE][NAS] Receive Registration Accept
![Screenshot from 2021-03-01 00-39-31](https://user-images.githubusercontent.com/34620715/109434526-c6590200-7a26-11eb-81b6-e963ed65d5e3.png)
![Screenshot from 2021-03-01 00-38-40](https://user-images.githubusercontent.com/34620715/109434534-cc4ee300-7a26-11eb-86d8-d800ca5fdaf9.png)
![Screenshot from 2021-03-01 00-38-48](https://user-images.githubusercontent.com/34620715/109434538-ceb13d00-7a26-11eb-9899-163dc21a65ee.png)
![Screenshot from 2021-03-01 00-38-54](https://user-images.githubusercontent.com/34620715/109434539-cf49d380-7a26-11eb-83c2-4898d5c2f864.png)
![Screenshot from 2021-03-01 00-38-57](https://user-images.githubusercontent.com/34620715/109434542-d1139700-7a26-11eb-8c78-45749c8224a7.png)
![Screenshot from 2021-03-01 00-39-18](https://user-images.githubusercontent.com/34620715/109434544-d244c400-7a26-11eb-8370-f70caacee6ef.png)




![Screenshot from 2021-03-01 00-38-44](https://user-images.githubusercontent.com/34620715/109434536-cce77980-7a26-11eb-8ff2-0706e545348d.png)

**Comment by noormohammedli** [comment]
Yes, It is register finally thank you very much 
![Screenshot from 2021-03-01 00-41-20](https://user-images.githubusercontent.com/34620715/109434586-0d46f780-7a27-11eb-80cf-43468e69f63f.png)

now if i need to add more users i need to update just the config file then i need to add the UE info in the web ui 
So

**Comment by baleeiro17** [comment]
Hi, checking your messages  I saw an error in your UPF.( this is why uetun1 is not display for you). Now the problem is in 5g core. What kernel are you using ? Please use "uname -r". Other question are you using namespaces?  The problem I think is in configuration of 5G core, version of docker will solve this because is automatized. Can you testing with docker for clear some questions? Show me "docker ps" and "docker-compose logs"

> If i need to add more users, I need to update just the config file then i need to add the UE info in the web ui.
You must add imsi 2089300000001 and 2089300000002 in web ui to testing 2 UEs registration. You does not need to update config file. The Tester will increment imsi begin in 2089300000001 for each UE. Please see wiki for more information.

> I really appreciate your help. Could you please send me your email address to discuss more about the slicing.
lucas.baleeiro@discente.ufg.br

**Comment by noormohammedli** [comment]
Hi, 
I run the docker file but tester container down, i tried to bring it up using 

sudo docker-compose down
sudo docker-compose up -d 


This is the kernel that i used 
![Screenshot from 2021-03-05 03-58-21](https://user-images.githubusercontent.com/34620715/110079076-b2503000-7d99-11eb-8ff1-b829528ea80c.png)

Show me "docker ps": 
![Screenshot from 2021-03-05 10-03-09](https://user-images.githubusercontent.com/34620715/110079298-00653380-7d9a-11eb-957c-2f30af2d7345.png)

docker-compose logs: 

![Screenshot from 2021-03-05 10-04-53](https://user-images.githubusercontent.com/34620715/110080202-3525ba80-7d9b-11eb-9ef7-80a344169f27.png)
![Screenshot from 2021-03-05 10-04-59](https://user-images.githubusercontent.com/34620715/110080205-35be5100-7d9b-11eb-8738-7bb8634a2399.png)
![Screenshot from 2021-03-05 10-05-10](https://user-images.githubusercontent.com/34620715/110080207-3656e780-7d9b-11eb-8a0b-1532f76345c1.png)
![Screenshot from 2021-03-05 10-05-13](https://user-images.githubusercontent.com/34620715/110080210-37881480-7d9b-11eb-808d-ee4202417c35.png)
![Screenshot from 2021-03-05 10-05-18](https://user-images.githubusercontent.com/34620715/110080215-38b94180-7d9b-11eb-8a96-12fe0b63c47d.png)
![Screenshot from 2021-03-05 10-05-24](https://user-images.githubusercontent.com/34620715/110080219-3951d800-7d9b-11eb-9b19-a1b2569eefb4.png)
![Screenshot from 2021-03-05 10-05-29](https://user-images.githubusercontent.com/34620715/110080223-39ea6e80-7d9b-11eb-99b5-d709a75eaef8.png)
![Screenshot from 2021-03-05 10-05-32](https://user-images.githubusercontent.com/34620715/110080227-3a830500-7d9b-11eb-8ce1-badf87ce08ed.png)
![Screenshot from 2021-03-05 10-05-35](https://user-images.githubusercontent.com/34620715/110080233-3bb43200-7d9b-11eb-9772-fb2e90390f29.png)
![Screenshot from 2021-03-05 10-05-38](https://user-images.githubusercontent.com/34620715/110080234-3ce55f00-7d9b-11eb-842b-9607cef793d9.png)
![Screenshot from 2021-03-05 10-05-40](https://user-images.githubusercontent.com/34620715/110080239-3d7df580-7d9b-11eb-8eb3-8def6e143e09.png)
![Screenshot from 2021-03-05 10-05-43](https://user-images.githubusercontent.com/34620715/110080241-3eaf2280-7d9b-11eb-85a9-346f73388662.png)
![Screenshot from 2021-03-05 10-06-08](https://user-images.githubusercontent.com/34620715/110080275-479ff400-7d9b-11eb-8f8a-51ac352c6806.png)

![Screenshot from 2021-03-05 10-06-04](https://user-images.githubusercontent.com/34620715/110080271-466ec700-7d9b-11eb-95f2-7adb8c0b461b.png)

![Screenshot from 2021-03-05 10-05-59](https://user-images.githubusercontent.com/34620715/110080266-45d63080-7d9b-11eb-9c7a-27288c95d209.png)

![Screenshot from 2021-03-05 10-05-46](https://user-images.githubusercontent.com/34620715/110080245-4078e600-7d9b-11eb-9180-44a763f88de4.png)
![Screenshot from 2021-03-05 10-05-49](https://user-images.githubusercontent.com/34620715/110080251-41aa1300-7d9b-11eb-8aaa-66c3457fbc1a.png)
![Screenshot from 2021-03-05 10-05-52](https://user-images.githubusercontent.com/34620715/110080255-4242a980-7d9b-11eb-9ed7-3f062406d7eb.png)
![Screenshot from 2021-03-05 10-05-55](https://user-images.githubusercontent.com/34620715/110080261-440c6d00-7d9b-11eb-8af9-4f37f50203aa.png)

![Screenshot from 2021-03-05 10-06-11](https://user-images.githubusercontent.com/34620715/110080283-48d12100-7d9b-11eb-9f94-ab257e3bce3a.png)
![Screenshot from 2021-03-05 10-06-13](https://user-images.githubusercontent.com/34620715/110080287-4a024e00-7d9b-11eb-99ba-063ef0c18251.png)
![Screenshot from 2021-03-05 10-06-17](https://user-images.githubusercontent.com/34620715/110080290-4bcc1180-7d9b-11eb-883a-cce994df2ad6.png)
![Screenshot from 2021-03-05 10-06-21](https://user-images.githubusercontent.com/34620715/110080297-4cfd3e80-7d9b-11eb-816f-df8e1baca28a.png)
![Screenshot from 2021-03-05 10-06-26](https://user-images.githubusercontent.com/34620715/110080302-4e2e6b80-7d9b-11eb-841f-2843581d6495.png)
![Screenshot from 2021-03-05 10-06-30](https://user-images.githubusercontent.com/34620715/110080306-4ec70200-7d9b-11eb-91c7-3e88d2dcdfeb.png)
![Screenshot from 2021-03-05 10-06-34](https://user-images.githubusercontent.com/34620715/110080308-4ff82f00-7d9b-11eb-9c21-3c3eb7854231.png)
![Screenshot from 2021-03-05 10-06-37](https://user-images.githubusercontent.com/34620715/110080311-51295c00-7d9b-11eb-971a-b06e1bc5233c.png)
![Screenshot from 2021-03-05 10-06-41](https://user-images.githubusercontent.com/34620715/110080317-525a8900-7d9b-11eb-87ec-719262df38c7.png)
![Screenshot from 2021-03-05 10-06-47](https://user-images.githubusercontent.com/34620715/110080319-538bb600-7d9b-11eb-8536-6870751b8ae4.png)
![Screenshot from 2021-03-05 10-06-50](https://user-images.githubusercontent.com/34620715/110080321-54bce300-7d9b-11eb-865e-381286044216.png)


List all docker container and image:

![Screenshot from 2021-03-05 10-21-19](https://user-images.githubusercontent.com/34620715/110081237-af0a7380-7d9c-11eb-9460-59d6169dffe5.png)

**Comment by noormohammedli** [comment]
Hello Sir, 

When I run my5G-core and my5G-RANTester or my5G-RANTester-docker do I need to run these steps as well. 

<img width="1119" alt="Screenshot 2021-03-07 at 10 48 44 pm" src="https://user-images.githubusercontent.com/34620715/110252800-2ce69e80-7f98-11eb-902d-7b0656b42730.png">

Regards, 
Noor Mohammedali.

**Comment by baleeiro17** [comment]
Hi sorry for delay answer. I was not healthy days ago.

> When I run my5G-core and my5G-RANTester or my5G-RANTester-docker do I need to run these steps as well.
No, you are correctly. It is not necessary.

Seeing your logs it seems 5g core is running and no problem is there. I updated code to solve one problem in my5g-Tester. It seems that ue is running before gnb. Now I think this will solve by new code. Can you please try testing again?

Execute the next steps:
`docker-compose down`
`docker rmi my5g-rantester-docker_tester`
`docker-compose up -d`

If you encounter some errors. Please check if you add the information in web ui(container webui must be running), test again with docker-compose down and docker-compose up -d. And show me tester's log. You can using the command:
`docker-compose logs tester`

Regards,
Lucas

**Comment by noormohammedli** [comment]
Hello  Lucas, 

Thank you for your help. I hope you doing well. 

I did all the steps. I have the uetun1 inside the container as the image below and the ping done successfully. 

![Screenshot from 2021-03-15 19-52-20](https://user-images.githubusercontent.com/34620715/111190396-18258e80-85c8-11eb-9f79-235eb2ca88b1.png)
 
![Screenshot from 2021-03-15 19-52-39](https://user-images.githubusercontent.com/34620715/111190433-22478d00-85c8-11eb-8de8-a5cacc5ccbd8.png)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
The tester's log 

![Screenshot from 2021-03-15 19-54-04](https://user-images.githubusercontent.com/34620715/111190554-4014f200-85c8-11eb-91e1-f3bb6c24cea9.png)

![Screenshot from 2021-03-15 19-54-15](https://user-images.githubusercontent.com/34620715/111190560-41461f00-85c8-11eb-82c2-6b967121f078.png)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 

I use the script include_ues.sh from my5G-RANTester-docker to add more than one user and i update the yml file as you explain in wiki 
In line 212 in docker-compose.yaml you can modify command and select another type of test(for example load-test -n 10. 

tester:
    container_name: tester
    build:
      context: ./nf_tester
    command: ./app load-test -n 10

![Screenshot from 2021-03-13 20-41-18](https://user-images.githubusercontent.com/34620715/111191473-29bb6600-85c9-11eb-91d6-e17e5eeeaebc.png)

![Screenshot from 2021-03-13 20-41-21](https://user-images.githubusercontent.com/34620715/111191489-2b852980-85c9-11eb-8d38-b423a9d153a1.png)


Then i show the The tester's log, I get the result as in the screen below. Is this correct ? , 

If I do the ping command from user 2 that means i need uetun2 to do the ping but i didnot get it inside the Tester container.  

![Screenshot from 2021-03-13 20-52-15](https://user-images.githubusercontent.com/34620715/111191607-4bb4e880-85c9-11eb-8064-6f72526dcd7a.png)
![Screenshot from 2021-03-13 20-52-18](https://user-images.githubusercontent.com/34620715/111191614-4ce61580-85c9-11eb-9466-ec99af7bcfd3.png)

Thanks,

**Comment by baleeiro17** [comment]
Hi , thanks Noor Mohammedali.

It seems with one UE registration worked fine.

> I use the script include_ues.sh from my5G-RANTester-docker to add more than one user and i update the yml file as you explain in wiki In line 212 in docker-compose.yaml you can modify command and select another type of test(for example load-test -n 10. 

Yes. You are correctly. Please check in your http://localhost:5000 if the script added all imsi(2089300000001,2089300000002, ...). You have to see uetun2, uetun3. Using the command below to added imsi:
`./include_ue.sh 10`

Seeing your logs, it seemed you did not use the latest version of my5G-RANTester. Did you use the command below?

`docker rmi my5g-rantester-docker_tester`

Can please show me the output of the command `docker images`?

You must delete all tester's images to update container docker with new code. 

Regards,
Lucas

**Comment by noormohammedli** [comment]
Hello, 
yes it is work now. 
I have 10 UEs in my web ui. 

I use "sudo docker rm [image id]" to delete the image and "sudo docker rm [container id]" to delete the container

![Screenshot from 2021-03-16 22-07-43](https://user-images.githubusercontent.com/34620715/111366197-437dab80-86a4-11eb-9327-642d1764b219.png)

![Screenshot from 2021-03-16 22-08-13](https://user-images.githubusercontent.com/34620715/111366217-47a9c900-86a4-11eb-9e29-5f39dc3f584b.png)

![Screenshot from 2021-03-16 22-08-30](https://user-images.githubusercontent.com/34620715/111366218-48425f80-86a4-11eb-916d-7b2ce521a901.png)
![Screenshot from 2021-03-16 22-10-22](https://user-images.githubusercontent.com/34620715/111366349-6dcf6900-86a4-11eb-9ae8-a0024c148b67.png)

**Comment by baleeiro17** [comment]
Yes, everything seems ok and you are now with latest version of my5G-RANTester.

**Comment by noormohammedli** [comment]
Hello, 

Yes, I have the last version, but I have a problem with the virtual interface, it disappeared from the tester container and all the UEs appear in web UI or the virtual interface appear in the Tester container and web UI but the ping failed. 

![image](https://user-images.githubusercontent.com/34620715/111850012-f8af9e00-8906-11eb-8b04-017fa27e3ce7.png)

When I turn the containers down using "sudo docker-compose down" my PC get panic when the running command. I tried another way which is deleting the container one after another and when I get to the UPF container picnic happened again.  
  
![20210319_230146](https://user-images.githubusercontent.com/34620715/111850147-63f97000-8907-11eb-93aa-8682e1a7dce7.jpg)

Regards, 

Noor

**Comment by baleeiro17** [comment]
> when I get to the UPF container picnic happened again.

Hey, it happened because of the kernel version. Free5gc supports kernel version 5.0.0-23-generic for UPF. Other versions is unstable and not officially supported by the free5gc team that developed UPF.

Please check your kernel version with `uname -r`

**Comment by noormohammedli** [comment]
Hi Sir, 
My kernel version is 5.8.0-45-generic.

**Comment by baleeiro17** [comment]
Hey Noor, you have to change kernel for one version supported, like 5.0.0-23-generic. And that problem will disappear.

**Comment by noormohammedli** [comment]
How can I change the kernel to 5.0.0-23-generic in ubuntu 20

**Comment by baleeiro17** [comment]
Hi Nor, I appended two links for you:

1- https://www.programmersought.com/article/78426799214/
2- https://itsfoss.com/upgrade-linux-kernel-ubuntu/ 

I used the second link. I had a problem in kernel 5.8 like you and downgrade to 5.4.90-050490-generic(https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4.90/amd64/). Now works fine with UPF.

Sorry for delay answer. I will respond your email as soon as possible.

**Comment by noormohammedli** [comment]
Hello Lucas,

Thank you for your email I will check it out.

Thanks
