### ISSUE TITLE
[Question] How to connect to 5GC

### ISSUE THREAD

**Issue by Evanlin1224** [my5G/my5G-RANTester#17]
Hellow @baleeiro17 ~
i want to use my5G-RANTester (VM 2)to connect my open5gs core (VM1). I have configured my config.yaml as following. I run ./ app gnb first. Then i run ./ app ue ,but it shows some error message that is "Error inaddress already in use". How should I do to fix it?
this is my config.yaml    <P.S. 192.168.50.10 is my open5gs core's ip>
![image](https://user-images.githubusercontent.com/62740649/120449710-43976880-c3c2-11eb-9078-ecd6e51101e0.png)

./app gnb
![image](https://user-images.githubusercontent.com/62740649/120449849-645fbe00-c3c2-11eb-8b01-893c8d61b0ad.png)

./app ue
![image](https://user-images.githubusercontent.com/62740649/120449989-8c4f2180-c3c2-11eb-9a67-c98971d0af98.png)

**Comment by baleeiro17** [comment]
Hi @Evanlin1224 ,thank you for your interest in project and sorry for delay answer.
The comand ./app ue will simulate a UE and an GNB at the same time. It is not necessary execute ./app gnb in separate. The purpose of this command is simulate a gnb without UE. In your case I think you have two process(gnb) running with the same ip and port. 

Other importante information is about IMSI, this must have 13 digits in config.yaml, you can use 9017000000001.

**Comment by Evanlin1224** [comment]
@baleeiro17  Thanks for your help. I tried modify my config.yaml as following. I used command ./app ue this time, but it shown "AMF is inactivate". Then I look open5gs log message, it shows "Cannot find S_NSSAI. Check amf.plmn_support.s_nssai". So I tried to change sst: "000001" in the config.yaml. And it shows strange message.

![image](https://user-images.githubusercontent.com/62740649/120663532-ad943880-c4bc-11eb-8623-b6a644e2f2ab.png)
![image](https://user-images.githubusercontent.com/62740649/120663572-b71da080-c4bc-11eb-9f4f-6f7707b4d341.png)
![image](https://user-images.githubusercontent.com/62740649/120663634-c69ce980-c4bc-11eb-807f-0dc0f3101e76.png)

change sst: "000001"
![image](https://user-images.githubusercontent.com/62740649/120664074-3612d900-c4bd-11eb-8a53-69e4904b8696.png)
![image](https://user-images.githubusercontent.com/62740649/120664122-41660480-c4bd-11eb-9cc1-513eaf1e45ba.png)
![image](https://user-images.githubusercontent.com/62740649/120665246-2e9fff80-c4be-11eb-88e7-7ee9f8854c2b.png)

**Comment by baleeiro17** [comment]
Hi @Evanlin1224, thank you for report those errors. In tester side had some wrong choices. But I resolved those issues in branch open5gs. Can please you testing again? In my environment worked fine. Before testing UE registration, can please verify if in /tmp has file named gnb.sock and if yes, please, remove. This is cause of the error in the first image.
About configurations that you have to insert in web ui, default values(imsi 901700000000001) in config.yaml will work fine but you can change if you prefer. 

Thank you for help the project, Lucas.

**Comment by andreaterni7** [comment]
Hello @baleeiro17, I have more or less the same issue. I copy-paste what I get when I run "sudo ./app ue":
"INFO[0000] my5G-RANTester version 1.0.1                 
INFO[0000] ---------------------------------------      
INFO[0000] [TESTER] Starting test function: Testing an ue attached with configuration 
INFO[0000] [TESTER][UE] Number of UEs: 1                
INFO[0000] [TESTER][GNB] Control interface IP/Port: 127.0.0.1/9487 
INFO[0000] [TESTER][GNB] Data interface IP/Port: 192.168.88.209/2152 
INFO[0000] [TESTER][AMF] AMF IP/Port: 127.0.0.5/38412   
INFO[0000] ---------------------------------------      
INFO[0000] [GNB] SCTP/NGAP service is running           
INFO[0000] [GNB] UNIX/NAS service is running            
encoding/hex: odd length hex string
encoding/hex: odd length hex string
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6c6351]

goroutine 8 [running]:
my5G-RANTester/internal/control_test_engine/gnb/nas/service.gnbListen(0xc000013860)
	/home/andrea/my5G-RANTester/internal/control_test_engine/gnb/nas/service/service.go:43 +0x71
created by my5G-RANTester/internal/control_test_engine/gnb/nas/service.InitServer
	/home/andrea/my5G-RANTester/internal/control_test_engine/gnb/nas/service/service.go:32 +0x103"
Thank you in advance for your help
