### ISSUE TITLE
Follow up on multiple UEs registration and other topics

### ISSUE THREAD

**Issue by classo88** [my5G/my5G-RANTester#2]
Hello,

Following the guidance you have provided me about increasing the UPF's buffer size, it seems it worked fine to register 100 UEs. My problem was, indeed that I needed to "make UPF" again so many thanks for this, in Free5GC they do not specify this.

Following with this subject, I have been assinged to study Free5GC capabilities, one of them is to study its limits in terms of the number of UEs registrated that it can support. Since it seems that increasing such buffer increases the maximum number of UEs allowed, my question is this: Have you got to any conclusion abouta maximum number of UEs that can be registered? What about the maximum number of UEs to be registered at the same time? I do not know if I will get to a conlcussion if I just keep rising the buffer and the number of UEs to register, both simultaneously and consecutively.

On the other subject I commented in the forum with you, I'm trying to conect the core network to internet, first with a single ping to, for instance, Google DNS (8.8.8.8). I have tried to put such address in the config file but I do not get a response. I guess something is wrog with my network configuration but I cannot find my error. The following script is used in my run.sh for the core network where you can see how I create and delete my network interfaces and iptables . My laptopt local IP address is 102.168.1.60 in the wlp2s0 interface:

sudo ifconfig eno1:amf 10.100.200.3 up
sudo ifconfig eno1:gnbn 10.100.255.39 up
sudo ifconfig eno1:smfp 192.168.2.1 up
sudo ifconfig eno1:upfp 192.168.2.2 up
sudo ifconfig eno1:gnbg 10.200.200.1 up up
sudo ifconfig eno1:upfg 10.200.200.102 up
sudo ifconfig eno1:ue 60.60.0.101 up

sudo sysctl -w net.ipv4.ip_forward=1

sudo iptables -t nat -A POSTROUTING -s 60.60.0.0/24 -j SNAT --to-source 192.168.1.60

sudo systemctl stop ufw

Then I only change amfcfg.config, smfcfg.config and upfcfg.yaml according such interfaces.

**amfcfg.config:**

configuration:
  amfName: AMF
  ngapIpList:
    - 10.100.200.3

**smfcfg.config:**

pfcp:
    addr: 10.200.200.1
  userplane_information:
    up_nodes:
      gNB1:
        type: AN
        an_ip: 192.188.2.3
      UPF:
        type: UPF
        node_id: 10.200.200.101
    links:
      - A: gNB1
        B: UPF
  ue_subnet: 60.60.0.0/16

**upfcfg.yaml:**

pfcp:
    - addr: 192.168.2.2

  gtpu:
    - addr: 10.200.200.102
    # [optional] gtpu.name
    # - name: upf.5gc.nctu.me
    # [optional] gtpu.ifname
    # - ifname: gtpif

  dnn_list:
    - dnn: internet
      cidr: 60.60.0.0/24
      # [optional] dnn_list[*].natifname
      natifname: wlp2s0

With all this setup I have read in the forums I should be able to get a ping to internet, but it doesn't seem to work. I cannot even ping to my gateway 192.168.1.1. Any ideas on this?

Something which I have found these last days is that if I read the traffic with Wireshark passing through these interfaces it  does not catch anything, all the traffic seems to go through the loopback interface but I do not understand why since if I do not create such interfaces the core does not start properly. the following shows my ifconfig:

eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:amf: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.100.200.3  netmask 255.0.0.0  broadcast 10.255.255.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:gnbg: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.200.200.1  netmask 255.0.0.0  broadcast 10.255.255.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:gnbn: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.100.255.39  netmask 255.0.0.0  broadcast 10.255.255.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:smfp: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.2.1  netmask 255.255.255.0  broadcast 192.168.2.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:ue: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 60.60.0.101  netmask 255.0.0.0  broadcast 60.255.255.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:upfg: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.200.200.102  netmask 255.0.0.0  broadcast 10.255.255.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

eno1:upfp: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.2.2  netmask 255.255.255.0  broadcast 192.168.2.255
        ether b8:ca:3a:d7:5b:82  txqueuelen 1000  (Ethernet)
        device interrupt 20  memory 0xf7e00000-f7e20000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 202863  bytes 1021824567 (1.0 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 202863  bytes 1021824567 (1.0 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

upfgtp: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet6 fe80::1b10:b665:a53c:a039  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 100  bytes 7600 (7.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 100  bytes 4800 (4.8 KB)
        TX errors 10  dropped 0 overruns 0  carrier 0  collisions 0

wlp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.60  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::da1d:331e:54da:adab  prefixlen 64  scopeid 0x20<link>
        ether 3c:a9:f4:0c:cd:84  txqueuelen 1000  (Ethernet)
        RX packets 39376  bytes 22515176 (22.5 MB)
        RX errors 0  dropped 17  overruns 0  frame 0
        TX packets 14098  bytes 3148792 (3.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Again thank you very much for the help offered.

**Comment by baleeiro17** [comment]
Hi sorry for the delay answer. What test of my5G RAN Tester are you using? Can you please show a pcapng(with icmp and gtp) or log? It will help we understand better the problem

**Comment by classo88** [comment]
Hi, here is the pcap from Wireshark when pinging 8.8.8.8. You cant see no reply is recieved. If I change ping address to 192.168.1.1 whcih is supposed to be my router address, it does not get a reply either. I only gets reply to my local machine (laptop) 192.168.60 or other UE preconfigured 60.60.0.101.

I cannot upload the pcap file so I have uploaded into googledrive so you can download it and check it if you wish to.

[https://drive.google.com/file/d/1DZ8fKDUXSQdz1KrSZ3hMlnovBf829ENj/view?usp=sharing, https://drive.google.com/file/d/1zswTx98zHRCw2WhL8yLcL4MY338bYbfH/view?usp=sharing](url)

Thank you

**Comment by baleeiro17** [comment]
Hey classo88, sorry for the delay answer. Can you check this page https://github.com/my5G/my5G-RANTester/wiki/Using-containers and testing m5G-RANTester with containers. I think that will solve your problem because we will use  the same environment and here works fine(with large number of ues too).
