### ISSUE TITLE
[Question] Maximum number of UEs

### ISSUE THREAD

**Issue by orion-belt** [my5G/my5G-RANTester#39]
Hi
What are the maximum number of UEs are supported or tested with [my5G-RANTester](https://github.com/my5G/my5G-RANTester) ?

**Comment by baleeiro17** [comment]
Hi @orion-belt sorry for delay answer. In this [work](http://www.repositorio.jesuita.org.br/handle/UNISINOS/9750?show=full), the authors use 200 UEs with my5G-RANTester..
