### ISSUE TITLE
How do I access UE s command line interface to test its connectivity and use the established PDU session?

### ISSUE THREAD

**Issue by pragnyakiri** [my5G/my5G-RANTester#4]
Hi ,
I am new to this field. So, these questions may sound too basic to you.
I am able to run./app ue and a pdu session is getting established successfully.
Hpw do i test this pdu session, for example can I login to UE's CLI and ping a website. Can I download some thing using wget from the internet via free5gc network.

Thank you

**Comment by baleeiro17** [comment]
Hi,
Now, you can change field ping in config/config.yml and check using wireshark(filter gtp and icmp) for example, if your ping will get reply. In the next releases we will add more functionality for data-plane.

**Comment by baleeiro17** [comment]
Please check wiki(https://github.com/my5G/my5G-RANTester/wiki), now you can using UE interface that tester will create for testing data plane as you want.
