### ISSUE TITLE
Error testing UE

### ISSUE THREAD

**Issue by kouamdo** [my5G/my5G-RANTester#46]
H , i'm tryung to test 3 UE knowing that i have install it using code source without container.
SO i have receive thus error: 
`FATA[0001] Error in[UE] Error on Dial with server%!(EXTRA *net.OpError=dial unix /tmp/gnb.sock: connect: no such file or directory)`

`root@5gran-test:~/my5G-RANTester/cmd# ./app load-test -n 3
INFO[0000] my5G-RANTester version 1.0.1
INFO[0000] ---------------------------------------
INFO[0000] [TESTER] Starting test function: Testing registration of multiple UEs
INFO[0000] [TESTER][UE] Number of UEs: 3
INFO[0000] [TESTER][GNB] gNodeB control interface IP/Port: 127.0.0.1/9487
INFO[0000] [TESTER][GNB] gNodeB data interface IP/Port: 127.0.0.1/2152
INFO[0000] [TESTER][AMF] AMF IP/Port: 5.161.73.127/80
INFO[0000] ---------------------------------------
INFO[0001] [TESTER] TESTING REGISTRATION USING IMSI 0000000001 UE
FATA[0001] Error in[UE] Error on Dial with server%!(EXTRA *net.OpError=dial unix /tmp/gnb.sock: connect: no such file or directory)
root@5gran-test:~/my5G-RANTester/cmd#`

**Comment by kouamdo** [comment]
what should i do ?

**Comment by kouamdo** [comment]
Hui , i have another kind of error , let me know how i can avoid it
`root@rantester:/home/ubuntu/my5G-RANTester/cmd# ./app load-test -n 3
INFO[0000] my5G-RANTester version 1.0.1
INFO[0000] ---------------------------------------
INFO[0000] [TESTER] Starting test function: Testing registration of multiple UEs
INFO[0000] [TESTER][UE] Number of UEs: 3
INFO[0000] [TESTER][GNB] gNodeB control interface IP/Port: 5.161.73.127/9487
INFO[0000] [TESTER][GNB] gNodeB data interface IP/Port: 5.161.73.127/9487
INFO[0000] [TESTER][AMF] AMF IP/Port: 5.161.73.127/38412
INFO[0000] ---------------------------------------
FATA[0000] Error incannot assign requested address
root@rantester:/home/ubuntu/my5G-RANTester/cmd#
`

**Comment by baleeiro17** [comment]
Hi @kouamdo, it seems the tester cannot assign requested address. The IP you set in configurations (controlif and dataif) is available in your machine/VM that you running the tester.  Other aspect, the AMF is running with 5.161.73.127/38412  before your running the tester. Please check these details!

**Comment by kouamdo** [comment]
I'm using container . I have used local IP address but nothing
